# -*- coding: utf-8 -*-
"""sportsCNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yZRQ4siCrN98UjT_Sf2E-NF50_Veg-KC
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install ultralytics
!pip install deep_sort_realtime opencv-python-headless

print("Class names:", model.names)

import cv2
from ultralytics import YOLO
from deep_sort_realtime.deepsort_tracker import DeepSort

# Load YOLOv11 model
model_path = "/content/drive/MyDrive/best.pt"
model = YOLO(model_path)
print("✅ YOLOv11 model loaded.")

# Load DeepSORT
tracker = DeepSort(max_age=10)
print("✅ DeepSORT initialized.")

# Open input video
video_path = "/content/drive/MyDrive/15sec_input_720p.mp4"
cap = cv2.VideoCapture(video_path)

width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
fps = cap.get(cv2.CAP_PROP_FPS)
out = cv2.VideoWriter("deepsort_output.avi", cv2.VideoWriter_fourcc(*'XVID'), fps, (width, height))

# Frame-by-frame tracking
while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        break

    # Run YOLOv11
    results = model(frame)[0]

    detections = []
    for det in results.boxes:
        cls = int(det.cls)
        conf = float(det.conf)
        class_name = model.names[cls]
        if class_name == 'player':
            x1, y1, x2, y2 = map(int, det.xyxy[0])
            bbox = [x1, y1, x2 - x1, y2 - y1]  # Format: [x, y, w, h]
            detections.append((bbox, conf, class_name))

    # Run DeepSORT
    tracks = tracker.update_tracks(detections, frame=frame)

    for track in tracks:
        if not track.is_confirmed():
            continue
        track_id = track.track_id
        x1, y1, x2, y2 = map(int, track.to_ltrb())
        cv2.rectangle(frame, (x1, y1), (x2, y2), (0, 255, 0), 2)
        cv2.putText(frame, f"ID {track_id}", (x1, y1 - 10),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0, 255, 0), 2)

    out.write(frame)

cap.release()
out.release()
print("✅ Video saved as deepsort_output.avi")

from google.colab import files
files.download("deepsort_output.avi")